/* DSblock model generated by Dymola from Modelica model Version_7.Vehicles.vehicle
 Dymola Version 2017 (64-bit), 2016-06-23 translated this at Sun Jan 01 10:46:37 2017

   */
#ifndef DYN_MULTINSTANCE
#define DYN_MULTINSTANCE 1
#endif

#include <matrixop.h>
/* Declaration of C-structs */
struct DymStruc0;
struct DymStruc0 {
  int  id_0member;
};
DYMOLA_STATIC struct DymStruc0 DymStruc0_construct(int   id_02) {
  struct DymStruc0 dummy_0;
  dummy_0.id_0member = id_02;
  return dummy_0;
}
/* Prototypes for functions used in model */
DYMOLA_STATIC double   Modelica_Blocks_Tables_CombiTable1Ds_getTableValue_M(
  struct DymStruc0 tableID0_0, int  icol0_0, double  u0_0, double  
  tableAvailable0_0);
DYMOLA_STATIC struct DymStruc0  Modelica_Blocks_Types_ExternalCombiTable1D_M(
  const char*  tableName0_0, const char*  fileName0_0, RealArray   table0_0, 
  IntegerArray   columns0_0, int  smoothness0_0, int id_, int alwaysMakeNew_);
DYMOLA_STATIC void Modelica_Blocks_Types_ExternalCombiTable1D_destructor_M(
  void* externalCombiTable1D0_0);
/* Codes used in model */

/* Flattened Modelica model:

function Modelica.Blocks.Tables.CombiTable1Ds.getTableValue
input Modelica.Blocks.Types.ExternalCombiTable1D tableID;
input Integer icol;
discrete input Real u;
discrete input Real tableAvailable "Dummy input to ensure correct sorting of function calls";
discrete output Real y;

external "C" y = ModelicaStandardTables_CombiTable1D_getValue(tableID, icol, u);
annotation(derivative(noDerivative=tableAvailable)=Modelica.Blocks.Tables.CombiTable1Ds.getDerTableValue, Library={"ModelicaMatIO", "ModelicaStandardTables", "zlib"}, LibraryDirectory="C:/Program Files (x86)/Dymola 2017/Modelica/Library/Modelica 3.2.2/Resources/Library");
end Modelica.Blocks.Tables.CombiTable1Ds.getTableValue;

  */
DYMOLA_STATIC double   Modelica_Blocks_Tables_CombiTable1Ds_getTableValue_M(
  struct DymStruc0 tableID0_0, int  icol0_0, double  u0_0, double  
  tableAvailable0_0) {
  PushContext("Modelica.Blocks.Tables.CombiTable1Ds.getTableValue")
  {
    /* Declare outputs and temporaries */
    double   y0_0;
    y0_0=0;
    /* Start of real code */
    {
      extern double (ModelicaStandardTables_CombiTable1D_getValue)(void*, int , 
        double );
      y0_0 = (ModelicaStandardTables_CombiTable1D_getValue)(externalTable_[
        tableID0_0.id_0member].obj_, icol0_0, u0_0);
      }
    /* Output section */
    PopContext()
    return y0_0;
  }}

/* Flattened Modelica model:

function Modelica.Blocks.Types.ExternalCombiTable1D
input String tableName "Table name";
input String fileName "File name";
discrete input Real table[:, :];
input Integer columns[:];
input Modelica.Blocks.Types.Smoothness smoothness;
output Modelica.Blocks.Types.ExternalCombiTable1D externalCombiTable1D;

external "C" externalCombiTable1D = ModelicaStandardTables_CombiTable1D_init(tableName, fileName, table, size(table, 1), size(table, 2), columns, size(columns, 1), smoothness);
annotation(Library={"ModelicaStandardTables"}, LibraryDirectory="C:/Program Files (x86)/Dymola 2017/Modelica/Library/Modelica 3.2.2/Resources/Library");
end Modelica.Blocks.Types.ExternalCombiTable1D;

  */
DYMOLA_STATIC struct DymStruc0  Modelica_Blocks_Types_ExternalCombiTable1D_M(
  const char*  tableName0_0, const char*  fileName0_0, RealArray   table0_0, 
  IntegerArray   columns0_0, int  smoothness0_0, int id_, int alwaysMakeNew_) {
  PushContext("Modelica.Blocks.Types.ExternalCombiTable1D")
  {
    /* Declare outputs and temporaries */
    struct DymStruc0  externalCombiTable1D0_0;
    externalCombiTable1D0_0.id_0member=0;
    /* Start of real code */
    {
      extern void* (ModelicaStandardTables_CombiTable1D_init)(const char* , 
        const char* , double  const *, size_t, size_t, int  const *, size_t, int );
      externalCombiTable1D0_0.id_0member=id_;
      if (externalTable_[id_].destructor_ && externalTable_[id_].obj_ && alwaysMakeNew_) {
      void*x_=externalTable_[id_].obj_;
      externalTable_[id_].obj_=0;
      (*(externalTable_[id_].destructor_))(x_);
      } else if (!externalTable_[id_].destructor_) {externalTable_[id_].obj_=0;}
      externalTable_[id_].destructor_=Modelica_Blocks_Types_ExternalCombiTable1D_destructor_M;

        if (!externalTable_[id_].obj_) externalTable_[id_].obj_ = (
        ModelicaStandardTables_CombiTable1D_init)(tableName0_0, fileName0_0, 
        table0_0.data, table0_0.dims[1-1], table0_0.dims[2-1], columns0_0.data, 
        columns0_0.dims[1-1], smoothness0_0);
      }
    /* Output section */
    PopContext()
    return externalCombiTable1D0_0;
  }}

/* Flattened Modelica model:

function Modelica.Blocks.Types.ExternalCombiTable1D.destructor
input Modelica.Blocks.Types.ExternalCombiTable1D externalCombiTable1D;

external "C" ModelicaStandardTables_CombiTable1D_close(externalCombiTable1D);
annotation(Library={"ModelicaStandardTables"}, LibraryDirectory="C:/Program Files (x86)/Dymola 2017/Modelica/Library/Modelica 3.2.2/Resources/Library");
end Modelica.Blocks.Types.ExternalCombiTable1D.destructor;

  */
DYMOLA_STATIC void Modelica_Blocks_Types_ExternalCombiTable1D_destructor_M(
  void* externalCombiTable1D0_0) {
  PushContext("Modelica.Blocks.Types.ExternalCombiTable1D.destructor")
  {
    /* Declare outputs and temporaries */
    /* Start of real code */
    {
      extern void (ModelicaStandardTables_CombiTable1D_close)(void*);
      (ModelicaStandardTables_CombiTable1D_close)(externalCombiTable1D0_0);
      }
    /* Output section */
    PopContext()
    return ;
  }}
/* DSblock C-code: */

#define NX_    9
#define NX2_   2
#define NU_    5
#define NY_    11
#define NW_    75
#define NP_    119
#define NPS_   0
#define MAXAuxStr_   2
#define MAXAuxStrLen_   500
#define NHash1_ -776208480
#define NHash2_ -1378364568
#define NHash3_ -2096525519
#define NI_    0
#define NRelF_ 7
#define NRel_  7
#define NTim_  0
#define NSamp_ 0
#define NCons_ 0
#define NA_    42
#define SizePre_ 1
#define SizeEq_ 7
#define SizeDelay_ 0
#define QNLmax_ 2
#define MAXAux 1
#define NrDymolaTimers_ 0
#define NWhen_ 2
#define NCheckIf_ 0
#define NGlobalHelp_ 144
#define NGlobalHelpI_ 46
#ifndef NExternalObject_
#define NExternalObject_ 1
#endif
#include <moutil.c>
PreNonAliasDef(0)
PreNonAliasDef(1)
PreNonAliasDef(2)
PreNonAliasDef(3)
PreNonAliasDef(4)
PreNonAliasDef(5)
#if !defined(DYM2CCUR)
 DYMOLA_STATIC const char*modelName="Version_7.Vehicles.vehicle";
#endif
DYMOLA_STATIC const char*usedLibraries[]={0};
DYMOLA_STATIC const char*dllLibraryPath[]={0};
DYMOLA_STATIC const char*default_dymosim_license_filename=
 "c:/users/patil/appdata/roaming/dynasim/dymola.lic";
DYMOLA_STATIC const char*GUIDString="{c98dc9c6-3154-4688-b56f-ffd331fe0859}";
DYMOLA_STATIC const double cvodeTolerance=1E-005;
#define QJacobianCGDef_ 1
DYMOLA_STATIC int QJacobianCG_[16]={6 , 3 , 1 , 6 , 7 , 2 , 2 , 4 , 1 , 3 , 1 , 5
   , 1 , 8 , 1 , 9};
DYMOLA_STATIC int QJacobianGC_[55]={
1 , 1 , 1 , 0 , 1 , 1 , 1 , 1 , 1 , 0 , 2 , 0 , 0 , 0 , 4 , 4 , 0 , 2 , 3 , 3 , 3
   , 0 , 3 , 3 , 3 , 3 , 3 , 5 , 5 , 5 , 5 , 5 , 0 , 0 , 5 , 5 , 8 , 8 , 8 , 0
   , 8 , 0 , 0 , 8 , 8 , 9 , 9 , 9 , 0 , 9 , 0 , 0 , 0 , 9 , 0};
DYMOLA_STATIC double QJacobianCD_[10]={0  , 44 , 50 , 54 , 70 , 64 , 99 , 110 , 77
   , 72};
#include <dsblock1.c>

/* Define variable names. */

#define Sections_
#define DIRECT_FEED_THROUGH 1

TranslatedEquations

InitialSection
#if defined(DynSimStruct) || defined(BUILDFMU)
DYNX(W_,0) = 3.141592653589793;
DYNX(W_,40) = 9.80665;
DYNX(W_,52) = 3.141592653589793;
DYNX(W_,66) = 3.141592653589793;
DYNX(W_,2) = 209.43951023931953;
DYNX(W_,3) = 62.83185307179586;
DYNX(W_,18) = 1;
#endif
DYNSetAuxString(did_, "NoName", 0);
DYNSetAuxString(did_, "NoName", 1);
#if defined(DynSimStruct) || defined(BUILDFMU)
DYNX(W_,20) = 2;
DYNX(W_,19) = false;
DYNX(W_,21) = 1;
DYNX(W_,69) = 0;
DYNX(W_,36) = 0;
DYNX(W_,64) = 0;
DYNX(W_,65) = 0;
DYNX(W_,59) = 0.0;
#endif
BoundParameterSection
DYNX(W_,1) = DYNX(DP_,88);
DYNX(W_,4) = DYNX(DP_,117);
DYNX(W_,24) = DYNX(DP_,118);
DYNX(W_,41) = divmacro(DYNX(DP_,88)*DYNX(DP_,90),"chassis.m*chassis.b",
  DYNX(DP_,89)+DYNX(DP_,90),"chassis.a+chassis.b");
DYNX(W_,42) = divmacro(DYNX(DP_,88)*DYNX(DP_,89),"chassis.m*chassis.a",
  DYNX(DP_,89)+DYNX(DP_,90),"chassis.a+chassis.b");
DYNX(W_,43) = divmacro(9.80665*DYNX(DP_,88)*DYNX(DP_,90),"9.80665*(chassis.m*chassis.b)",
  DYNX(DP_,89)+DYNX(DP_,90),"chassis.a+chassis.b");
DYNX(W_,44) = divmacro(9.80665*DYNX(DP_,88)*DYNX(DP_,89),"9.80665*(chassis.m*chassis.a)",
  DYNX(DP_,89)+DYNX(DP_,90),"chassis.a+chassis.b");
InitialBoundSection
{
  struct DymStruc0 dummy_DymStruc0;
  dummy_DymStruc0 = (PushModelContext(1,"Modelica.Blocks.Types.ExternalCombiTable1D(\"NoName\", \"NoName\", trans.tab_torque.table, trans.tab_torque.columns, Modelica.Blocks.Types.Smoothness.LinearSegments, 0, 1)")
    Modelica_Blocks_Types_ExternalCombiTable1D_M("NoName", "NoName", 
    RealTemporaryDense( &DYNX(DP_,13), 2, 17, 2), IntegerTemporaryDense( 
    &DYNX(W_,20), 1, 1), 1, 0, 1));
  DYNX(W_,22) = dummy_DymStruc0.id_0member;
PopAllMarks();
}
BoundParameterSection
InitialSection
#if defined(DynSimStruct) || defined(BUILDFMU)
DYNX(W_,6) = 0;
DYNX(W_,15) = 62.83185307179586;
DYNX(W_,26) = 0;
DYNX(W_,47) = 0.0;
DYNX(W_,48) = 0.0;
DYNX(W_,53) = 0.0;
DYNX(W_,67) = 0.0;
DYNX(Y_,2) = 0;
DYNX(Y_,3) = 0;
DYNX(Y_,7) = 0;
DYNX(Y_,10) = 0;
#endif
InitialSection
InitialStartSection
InitialStartSection2
DYNX(W_,25) = DYNX(W_,24);
DYNX(X_,0) = DYNX(DP_,110);
DYNX(X_,7) = divmacro(DYNX(DP_,110),"wheel1.vx0",DYNX(DP_,107),"wheel1.rw");
DYNX(X_,8) = divmacro(DYNX(DP_,115),"wheel2.vx0",DYNX(DP_,112),"wheel2.rw");
DYNX(Y_,0) = DYNX(DP_,96);
DYNX(Y_,8) = DYNX(W_,24);
InitialSection
DefaultSection
InitializeData(0)
InitialSection
DYNX(Aux_,0) = DYNX(W_,25);
InitialSection
InitialSection2
DYNX(W_,1) = DYNX(DP_,88);
DYNX(W_,4) = DYNX(DP_,117);
DYNX(W_,41) = divmacro(DYNX(DP_,88)*DYNX(DP_,90),"chassis.m*chassis.b",
  DYNX(DP_,89)+DYNX(DP_,90),"chassis.a+chassis.b");
DYNX(W_,42) = divmacro(DYNX(DP_,88)*DYNX(DP_,89),"chassis.m*chassis.a",
  DYNX(DP_,89)+DYNX(DP_,90),"chassis.a+chassis.b");
DYNX(W_,43) = divmacro(9.80665*DYNX(DP_,88)*DYNX(DP_,90),"9.80665*(chassis.m*chassis.b)",
  DYNX(DP_,89)+DYNX(DP_,90),"chassis.a+chassis.b");
DYNX(W_,44) = divmacro(9.80665*DYNX(DP_,88)*DYNX(DP_,89),"9.80665*(chassis.m*chassis.a)",
  DYNX(DP_,89)+DYNX(DP_,90),"chassis.a+chassis.b");
DYNX(W_,24) = DYNX(DP_,118);
DYNX(W_,23) = 0.0;
  {
    DYNX(W_,23) = 1.0;
  }
DYNX(X_,7) = divmacro(DYNX(DP_,110),"wheel1.vx0",DYNX(DP_,107),"wheel1.rw");
DYNX(X_,0) = DYNX(DP_,110);
DYNX(X_,8) = divmacro(DYNX(DP_,115),"wheel2.vx0",DYNX(DP_,112),"wheel2.rw");
InitialSection
DYNX(Aux_,0) = DYNX(W_,24);
InitialSection2
DYNX(W_,25) = DYNX(Aux_,0);
InitialBoundSection
{
  struct DymStruc0 dummy_DymStruc0;
  dummy_DymStruc0 = (PushModelContext(1,"Modelica.Blocks.Types.ExternalCombiTable1D(\"NoName\", \"NoName\", trans.tab_torque.table, trans.tab_torque.columns, Modelica.Blocks.Types.Smoothness.LinearSegments, 0, 1)")
    Modelica_Blocks_Types_ExternalCombiTable1D_M("NoName", "NoName", 
    RealTemporaryDense( &DYNX(DP_,13), 2, 17, 2), IntegerTemporaryDense( 
    &DYNX(W_,20), 1, 1), 1, 0, 1));
  DYNX(W_,22) = dummy_DymStruc0.id_0member;
PopAllMarks();
}
InitialSection
InitialSection2
DYNX(Y_,0) = DYNX(X_,0);
DYNX(W_,73) =  -divmacro(DYNX(X_,0)-DYNX(X_,8)*DYNX(DP_,112),"trans.Vx-wheel2.omega*wheel2.rw",
  RealBmax(fabs(DYNX(X_,8)*DYNX(DP_,112)), 0.01),"max(abs(wheel2.omega*wheel2.rw), 0.01)");
DYNX(W_,67) = DYNX(X_,2)-DYNX(X_,4)*DYNX(DP_,90);
DYNX(W_,74) =  -divmacro(DYNX(W_,67),"wheel2.Vy",RealBmax(fabs(DYNX(X_,8)*
  DYNX(DP_,112)), 0.01),"max(abs(wheel2.omega*wheel2.rw), 0.01)");
DYNX(W_,71) = sqrtGuarded(sqr(DYNX(W_,73))+sqr(DYNX(W_,74)),"wheel2.sx^2+wheel2.sy^2");
DYNX(W_,72) = 0.6366197723675814*atan(0.6366197723675814*DYNX(DP_,113)*
  DYNX(W_,71));
DYNX(W_,68) = DYNX(DP_,114)*DYNX(W_,44)*DYNX(W_,72);
DYNX(Y_,1) = divmacro((DYNX(DP_,112)*DYNX(X_,8)-DYNX(X_,0))*DYNX(W_,68),
  "(wheel2.rw*wheel2.omega-trans.Vx)*wheel2.Fxy",RealBmax(sqrtGuarded(sqr(
  DYNX(DP_,112)*DYNX(X_,8)-DYNX(X_,0))+sqr(DYNX(W_,67)),"(wheel2.rw*wheel2.omega-trans.Vx)^2+wheel2.Vy^2"),
   0.01),"max(sqrt((wheel2.rw*wheel2.omega-trans.Vx)^2+wheel2.Vy^2), 0.01)");
DYNX(Y_,2) = DYNX(X_,5);
DYNX(Y_,3) = DYNX(X_,6);
DYNX(Y_,6) = divmacro(DYNX(U_,2),"swa",DYNX(DP_,92),"chassis.i_s");
DYNX(W_,53) = DYNX(X_,2)+DYNX(X_,4)*DYNX(DP_,89);
DYNX(W_,54) = DYNX(X_,0)*cos(DYNX(Y_,6))+DYNX(W_,53)*sin(DYNX(Y_,6));
DYNX(W_,62) =  -divmacro(DYNX(W_,54)-DYNX(X_,7)*DYNX(DP_,107),"wheel1.vx-wheel1.omega*wheel1.rw",
  RealBmax(fabs(DYNX(X_,7)*DYNX(DP_,107)), 0.01),"max(abs(wheel1.omega*wheel1.rw), 0.01)");
DYNX(W_,55) = DYNX(W_,53)*cos(DYNX(Y_,6))-DYNX(X_,0)*sin(DYNX(Y_,6));
DYNX(W_,63) =  -divmacro(DYNX(W_,55),"wheel1.vy",RealBmax(fabs(DYNX(X_,7)*
  DYNX(DP_,107)), 0.01),"max(abs(wheel1.omega*wheel1.rw), 0.01)");
DYNX(W_,60) = sqrtGuarded(sqr(DYNX(W_,62))+sqr(DYNX(W_,63)),"wheel1.sx^2+wheel1.sy^2");
DYNX(W_,61) = 0.6366197723675814*atan(0.6366197723675814*DYNX(DP_,108)*
  DYNX(W_,60));
DYNX(W_,56) = DYNX(DP_,109)*DYNX(W_,43)*DYNX(W_,61);
DYNX(W_,57) = divmacro((DYNX(DP_,107)*DYNX(X_,7)-DYNX(W_,54))*DYNX(W_,56),
  "(wheel1.rw*wheel1.omega-wheel1.vx)*wheel1.Fxy",RealBmax(sqrtGuarded(sqr(
  DYNX(DP_,107)*DYNX(X_,7)-DYNX(W_,54))+sqr(DYNX(W_,55)),"(wheel1.rw*wheel1.omega-wheel1.vx)^2+wheel1.vy^2"),
   0.01),"max(sqrt((wheel1.rw*wheel1.omega-wheel1.vx)^2+wheel1.vy^2), 0.01)");
DYNX(W_,58) =  -divmacro(DYNX(W_,55)*DYNX(W_,56),"wheel1.vy*wheel1.Fxy",RealBmax
  (sqrtGuarded(sqr(DYNX(DP_,107)*DYNX(X_,7)-DYNX(W_,54))+sqr(DYNX(W_,55)),
  "(wheel1.rw*wheel1.omega-wheel1.vx)^2+wheel1.vy^2"), 0.01),"max(sqrt((wheel1.rw*wheel1.omega-wheel1.vx)^2+wheel1.vy^2), 0.01)");
DYNX(W_,45) = cos(DYNX(Y_,6))*DYNX(W_,57)-sin(DYNX(Y_,6))*DYNX(W_,58);
DYNX(W_,48) = (-0.5)*(IF DYNX(X_,0) > 0 THEN 1 ELSE IF DYNX(X_,0) < 0 THEN -1
   ELSE 0)*DYNX(DP_,100)*DYNX(DP_,101)*DYNX(DP_,102)*sqr(DYNX(X_,0));
DYNX(W_,47) = (-9.80665)*DYNX(DP_,99)*DYNX(DP_,88)*RealBmin(1, DYNX(X_,0));
DYNX(W_,49) = (-9.80665)*DYNX(DP_,88)*sin(DYNX(U_,3));
DYNX(W_,51) = 0.5*(DYNX(X_,7)+DYNX(X_,8));
DYNX(W_,14) = DYNX(W_,45)+DYNX(Y_,1)+DYNX(W_,48)+DYNX(W_,47)+DYNX(W_,49)*tanh(10
  *fabs(DYNX(W_,51)))*tanh(0.5*fabs(DYNX(X_,0)));
 /* Linear system of equations to solve. */
DYNX(Y_,4) = 0.0;
SolveScalarLinear(DYNX(DP_,88),"chassis.m", DYNX(W_,14),"trans.Fx", DYNX(Y_,4),
  "ax");
 /* End of Equation Block */ 

DYNX(Y_,5) = sin(DYNX(Y_,6))*DYNX(W_,57)+cos(DYNX(Y_,6))*DYNX(W_,58);
DYNX(Y_,7) = IF Greater(DYNX(Y_,4),"ax", 0,"0", 0) THEN 0 ELSE DYNX(Y_,4);
DYNX(W_,46) =  -divmacro(DYNX(W_,67)*DYNX(W_,68),"wheel2.Vy*wheel2.Fxy",RealBmax
  (sqrtGuarded(sqr(DYNX(DP_,112)*DYNX(X_,8)-DYNX(X_,0))+sqr(DYNX(W_,67)),
  "(wheel2.rw*wheel2.omega-trans.Vx)^2+wheel2.Vy^2"), 0.01),"max(sqrt((wheel2.rw*wheel2.omega-trans.Vx)^2+wheel2.Vy^2), 0.01)");
 /* Linear system of equations to solve. */
DYNX(Y_,9) = 0.0;
SolveScalarLinear(DYNX(DP_,88),"chassis.m", DYNX(Y_,5)+DYNX(W_,46),
  "Fyf+chassis.Fyr", DYNX(Y_,9),"ay");
 /* End of Equation Block */ 

DYNX(Y_,10) = DYNX(X_,4);
DYNX(W_,50) = 0.01*DYNX(U_,1)*DYNX(DP_,95);
 /* Linear system of equations to solve. */
DYNX(F_,7) = 0.0;
SolveScalarLinear(DYNX(DP_,111),"wheel1.I_tyre",  -(tanh(10*DYNX(X_,7))*tanh(0.5
  *fabs(DYNX(W_,54)))*DYNX(W_,50)+DYNX(W_,57)*DYNX(DP_,107))," -(tanh(10*wheel1.omega)*tanh(0.5*abs(wheel1.vx))*chassis.Tbw+wheel1.Fxw*wheel1.rw)",
   DYNX(F_,7),"der(wheel1.omega)");
 /* End of Equation Block */ 

DYNX(F_,0) = DYNX(Y_,4)+DYNX(X_,2)*DYNX(X_,4);
DYNX(W_,39) = IF Greater(DYNX(U_,4),"r_gear", 0,"0", 1) THEN 1 ELSE 0;
DYNX(W_,34) = 0.5*(DYNX(X_,7)+DYNX(X_,8));
DYNX(W_,32) = DYNX(W_,34)*DYNX(DP_,60);
DYNX(W_,30) = DYNX(W_,32)*RealElement( RealTemporaryDense( &DYNX(DP_,48), 1, 12),
   (SizeType)(DYNX(W_,25)));
PopAllMarks();
DYNX(W_,5) = RealBmax(RealBmin(0.01*DYNX(U_,0), 1), 0.0);
DYNX(W_,15) = RealBmin(209.43951023931953, RealBmax(DYNX(W_,30), 
  62.83185307179586));
DYNX(W_,8) = (PushModelContext(1,"Modelica.Blocks.Tables.CombiTable1Ds.getTableValue(\ntrans.tab_torque.tableID, \n1, \ntrans.w_engine, \ntrans.tab_torque.tableOnFileRead)")
  Modelica_Blocks_Tables_CombiTable1Ds_getTableValue_M(DymStruc0_construct(
  (Integer)(DYNX(W_,22))), 1, DYNX(W_,15), DYNX(W_,23)));
PopModelContext();
DYNX(W_,9) = IF Greater(DYNX(F_,0),"der(trans.Vx)", DYNX(DP_,8),"trans.axh", 2)
   THEN DYNX(DP_,10)*DYNX(W_,8) ELSE IF Less(DYNX(F_,0),"der(trans.Vx)", 
  DYNX(DP_,9),"trans.axl", 3) THEN DYNX(W_,8) ELSE DYNX(W_,8)*(1+divmacro((
  DYNX(F_,0)-DYNX(DP_,9))*(DYNX(DP_,10)-1),"(der(trans.Vx)-trans.axl)*(trans.E_factor-1)",
  DYNX(DP_,8)-DYNX(DP_,9),"trans.axh-trans.axl"));
DYNX(W_,6) = DYNX(W_,5)*DYNX(W_,9)*(1-tanh(0.01*(DYNX(W_,15)-209.43951023931953)))
  *DYNX(W_,4);
DYNX(W_,11) = RealBmin(DYNX(W_,6), DYNX(DP_,11));
DYNX(W_,13) = DYNX(W_,11)+DYNX(X_,1);
DYNX(W_,7) = IF DYNX(X_,0) < 0 THEN RealBmax(0, DYNX(W_,13)) ELSE DYNX(W_,13);

{ /* Non-linear system of equations to solve. */
  /* Nonlinear system of equations number = 1. */
/* Introducing 6 common subexpressions used in 7 expressions */
/* Of the common subexpressions 3 are reals, 0 are integers, and 3
   are booleans. */
const char*const varnames_[]={"wheel2.der(omega)"};
const double nominal_[]={1};
NonLinearSystemOfEquations(Jacobian__, residue__, x__, 1, 0, 1, 8, 
  DYNX(DYNhelp,0), 35, DYNX(did_->helpvari_vec,0), 23);
SetInitVectorSimple(x__, 1, DYNX(F_,8), 0.0);
Residues;
  DYNX(W_,35) = 0.5*(DYNX(F_,7)+DYNX(F_,8));
  DYNX(W_,33) = DYNX(W_,35)*DYNX(DP_,60);
  DYNX(DYNhelp,35) = RealElement( RealTemporaryDense( &DYNX(DP_,48), 1, 12), 
    (SizeType)(DYNX(W_,25)));
  PopAllMarks();
  DYNX(W_,31) = DYNX(W_,33)*DYNX(DYNhelp,35);
  DYNX(DYNhelp,36) = 209.43951023931953 < RealBmax(DYNX(W_,30), 62.83185307179586);
  DYNX(W_,16) = IF DYNX(DYNhelp,36) THEN 0.0 ELSE IF DYNX(W_,30) > 
    62.83185307179586 THEN DYNX(W_,31) ELSE 0.0;
  DYNX(W_,27) = DYNX(W_,7)-DYNX(DP_,106)*DYNX(W_,16);
  DYNX(W_,28) = DYNX(W_,27)*DYNX(DYNhelp,35);
  DYNX(W_,29) = DYNX(DP_,61)*DYNX(W_,28)*DYNX(DP_,60);
  DYNX(W_,37) = RealBmax(DYNX(W_,29), 0);
  DYNX(DYNhelp,37) = 1*DYNX(W_,39);
  DYNX(W_,38) =  -DYNX(DYNhelp,37)*RealBmax(DYNX(W_,27), 0)*DYNX(DP_,53)*
    DYNX(DP_,60);
  DYNX(DYNhelp,38) = Equal(DYNX(U_,4), 1, 4);
  DYNX(W_,70) = IF DYNX(DYNhelp,38) THEN DYNX(W_,38) ELSE DYNX(W_,37);
SetVector(residue__, 1, DYNX(DP_,116)*DYNX(F_,8)-DYNX(W_,70)+tanh(10*DYNX(X_,8))
  *tanh(0.5*fabs(DYNX(X_,0)))*DYNX(W_,50)+DYNX(Y_,1)*DYNX(DP_,112));

Jacobian(Jacobian__)
MatrixZeros(Jacobian__);
DYNX(DYNhelp,39) = DYNX(W_,27) > 0;
DYNX(DYNhelp,40) = DYNX(DP_,106)*(DYNX(DYNhelp,35)*DYNX(DP_,60)*DYNX(DP_,61)*(
  IF DYNX(W_,29) > 0 THEN 1.0 ELSE 0.0)*(IF DYNX(DYNhelp,38) THEN 0.0 ELSE 1.0)-
  DYNX(DP_,60)*DYNX(DP_,53)*DYNX(DYNhelp,37)*(IF DYNX(DYNhelp,39) THEN 1.0 ELSE 
  0.0)*(IF DYNX(DYNhelp,38) THEN 1.0 ELSE 0.0));
SetMatrixLeading(Jacobian__, 1, 1, 1, DYNX(DP_,116)+0.5*DYNX(DP_,60)*
  DYNX(DYNhelp,35)*(IF DYNX(DYNhelp,36) THEN 0.0 ELSE IF DYNX(W_,30) > 
  62.83185307179586 THEN 1.0 ELSE 0.0)*DYNX(DYNhelp,40));

SolveNonLinearSystemOfEquationsInit(Jacobian__, residue__, x__);
DYNX(F_,8) = GetVector(x__, 1);
EndNonLinearSystemOfEquationsInit(residue__, x__, 1);
 /* End of Non-Linear Equation Block */ }



DYNX(W_,12) = DYNX(W_,6)-DYNX(W_,11);
DYNX(F_,1) = DYNX(DP_,12)*(DYNX(W_,12)-DYNX(X_,1));
 /* Linear system of equations to solve. */
DYNX(F_,4) = 0.0;
SolveScalarLinear(DYNX(DP_,91),"chassis.Izz", DYNX(DP_,89)*DYNX(Y_,5)-
  DYNX(DP_,90)*DYNX(W_,46),"chassis.a*Fyf-chassis.b*chassis.Fyr", DYNX(F_,4),
  "der(chassis.yaw_velocity)");
 /* End of Equation Block */ 

DYNX(F_,2) = DYNX(Y_,9)-DYNX(X_,0)*DYNX(X_,4);
DYNX(F_,3) = DYNX(X_,4);
DYNX(F_,5) = DYNX(X_,0)*cos(DYNX(X_,3))-DYNX(X_,2)*sin(DYNX(X_,3));
DYNX(F_,6) = DYNX(X_,2)*cos(DYNX(X_,3))+DYNX(X_,0)*sin(DYNX(X_,3));
DYNX(Y_,8) = DYNX(W_,25);
InitialSection2
Init_=false;InitializeData(2);Init_=true;
EndInitialSection

OutputSection
DYNX(Y_,0) = DYNX(X_,0);
DYNX(DYNhelp,41) = DYNX(X_,8)*DYNX(DP_,112);
DYNX(DYNhelp,42) = fabs(DYNX(DYNhelp,41));
DYNX(DYNhelp,43) = RealBmax(DYNX(DYNhelp,42), 0.01);
DYNX(DYNhelp,44) = divmacro(1.0,"1.0",DYNX(DYNhelp,43),"max(abs(wheel2.omega*wheel2.rw), 0.01)");
DYNX(W_,73) =  -DYNX(DYNhelp,44)*(DYNX(X_,0)-DYNX(DYNhelp,41));
DYNX(W_,67) = DYNX(X_,2)-DYNX(X_,4)*DYNX(DP_,90);
DYNX(DYNhelp,45) = divmacro(1.0,"1.0",DYNX(DYNhelp,43),"max(abs(wheel2.omega*wheel2.rw), 0.01)");
DYNX(W_,74) =  -DYNX(DYNhelp,45)*DYNX(W_,67);
DYNX(W_,71) = sqrtGuarded(sqr(DYNX(W_,73))+sqr(DYNX(W_,74)),"wheel2.sx^2+wheel2.sy^2");
DYNX(DYNhelp,46) = atan(0.6366197723675814*DYNX(DP_,113)*DYNX(W_,71));
DYNX(W_,72) = 0.6366197723675814*DYNX(DYNhelp,46);
DYNX(W_,68) = DYNX(DP_,114)*DYNX(W_,44)*DYNX(W_,72);
DYNX(DYNhelp,47) = DYNX(DP_,112)*DYNX(X_,8)-DYNX(X_,0);
DYNX(DYNhelp,48) = sqrtGuarded(sqr(DYNX(DYNhelp,47))+sqr(DYNX(W_,67)),
  "(wheel2.rw*wheel2.omega-trans.Vx)^2+wheel2.Vy^2");
DYNX(DYNhelp,49) = RealBmax(DYNX(DYNhelp,48), 0.01);
DYNX(DYNhelp,50) = divmacro(1.0,"1.0",DYNX(DYNhelp,49),"max(sqrt((wheel2.rw*wheel2.omega-trans.Vx)^2+wheel2.Vy^2), 0.01)");
DYNX(Y_,1) = DYNX(DYNhelp,50)*DYNX(DYNhelp,47)*DYNX(W_,68);
DYNX(Y_,2) = DYNX(X_,5);
DYNX(Y_,3) = DYNX(X_,6);
DYNX(W_,53) = DYNX(X_,2)+DYNX(X_,4)*DYNX(DP_,89);
DYNX(W_,48) = (-0.5)*(IF DYNX(X_,0) > 0 THEN 1 ELSE IF DYNX(X_,0) < 0 THEN -1
   ELSE 0)*DYNX(DP_,100)*DYNX(DP_,101)*DYNX(DP_,102)*sqr(DYNX(X_,0));
DYNX(DYNhelp,51) = RealBmin(1, DYNX(X_,0));
DYNX(W_,47) = (-9.80665)*DYNX(DP_,99)*DYNX(DP_,88)*DYNX(DYNhelp,51);
DYNX(W_,51) = 0.5*(DYNX(X_,7)+DYNX(X_,8));
DYNX(DYNhelp,52) = divmacro(1.0,"1.0",DYNX(DYNhelp,49),"max(sqrt((wheel2.rw*wheel2.omega-trans.Vx)^2+wheel2.Vy^2), 0.01)");
DYNX(W_,46) =  -DYNX(DYNhelp,52)*DYNX(W_,67)*DYNX(W_,68);
DYNX(Y_,10) = DYNX(X_,4);
DYNX(W_,25) = PRE(DYNX(W_,25), 0);
  beginwhenBlock
  whenModelica(GreaterMinor(DYNX(X_,0),"trans.Vx", RealElement( RealTemporaryDense( 
    &DYNX(DP_,62), 1, 12), (SizeType)(PRE(DYNX(W_,25), 0))),"trans.upshift[pre(trans.agear)]",
     5), 0) 
    DYNX(W_,25) = PRE(DYNX(W_,25), 0)+1;
  endwhenModelica()

  PopAllMarks();
  whenModelica(LessMinor(DYNX(X_,0),"trans.Vx", RealElement( RealTemporaryDense( 
    &DYNX(DP_,74), 1, 12), (SizeType)(PRE(DYNX(W_,25), 0))),"trans.downshift[pre(trans.agear)]",
     6), 1) 
    DYNX(W_,25) = PRE(DYNX(W_,25), 0)-1;
  endwhenModelica()
  endwhenBlock

  PopAllMarks();
DYNX(Y_,8) = DYNX(W_,25);
DYNX(Y_,6) = divmacro(DYNX(U_,2),"swa",DYNX(DP_,92),"chassis.i_s");
DYNX(DYNhelp,53) = cos(DYNX(Y_,6));
DYNX(DYNhelp,54) = sin(DYNX(Y_,6));
DYNX(W_,54) = DYNX(X_,0)*DYNX(DYNhelp,53)+DYNX(W_,53)*DYNX(DYNhelp,54);
DYNX(DYNhelp,55) = DYNX(X_,7)*DYNX(DP_,107);
DYNX(DYNhelp,56) = fabs(DYNX(DYNhelp,55));
DYNX(DYNhelp,57) = RealBmax(DYNX(DYNhelp,56), 0.01);
DYNX(DYNhelp,58) = divmacro(1.0,"1.0",DYNX(DYNhelp,57),"max(abs(wheel1.omega*wheel1.rw), 0.01)");
DYNX(W_,62) =  -DYNX(DYNhelp,58)*(DYNX(W_,54)-DYNX(DYNhelp,55));
DYNX(W_,55) = DYNX(W_,53)*DYNX(DYNhelp,53)-DYNX(X_,0)*DYNX(DYNhelp,54);
DYNX(DYNhelp,59) = divmacro(1.0,"1.0",DYNX(DYNhelp,57),"max(abs(wheel1.omega*wheel1.rw), 0.01)");
DYNX(W_,63) =  -DYNX(DYNhelp,59)*DYNX(W_,55);
DYNX(W_,60) = sqrtGuarded(sqr(DYNX(W_,62))+sqr(DYNX(W_,63)),"wheel1.sx^2+wheel1.sy^2");
DYNX(DYNhelp,60) = atan(0.6366197723675814*DYNX(DP_,108)*DYNX(W_,60));
DYNX(W_,61) = 0.6366197723675814*DYNX(DYNhelp,60);
DYNX(W_,56) = DYNX(DP_,109)*DYNX(W_,43)*DYNX(W_,61);
DYNX(DYNhelp,61) = DYNX(DP_,107)*DYNX(X_,7)-DYNX(W_,54);
DYNX(DYNhelp,62) = sqrtGuarded(sqr(DYNX(DYNhelp,61))+sqr(DYNX(W_,55)),
  "(wheel1.rw*wheel1.omega-wheel1.vx)^2+wheel1.vy^2");
DYNX(DYNhelp,63) = RealBmax(DYNX(DYNhelp,62), 0.01);
DYNX(DYNhelp,64) = divmacro(1.0,"1.0",DYNX(DYNhelp,63),"max(sqrt((wheel1.rw*wheel1.omega-wheel1.vx)^2+wheel1.vy^2), 0.01)");
DYNX(W_,57) = DYNX(DYNhelp,64)*DYNX(DYNhelp,61)*DYNX(W_,56);
DYNX(DYNhelp,65) = divmacro(1.0,"1.0",DYNX(DYNhelp,63),"max(sqrt((wheel1.rw*wheel1.omega-wheel1.vx)^2+wheel1.vy^2), 0.01)");
DYNX(W_,58) =  -DYNX(DYNhelp,65)*DYNX(W_,55)*DYNX(W_,56);
DYNX(W_,45) = DYNX(DYNhelp,53)*DYNX(W_,57)-DYNX(DYNhelp,54)*DYNX(W_,58);
DYNX(DYNhelp,66) = sin(DYNX(U_,3));
DYNX(W_,49) = (-9.80665)*DYNX(DP_,88)*DYNX(DYNhelp,66);
DYNX(DYNhelp,67) = fabs(DYNX(W_,51));
DYNX(DYNhelp,68) = tanh(10*DYNX(DYNhelp,67));
DYNX(DYNhelp,69) = fabs(DYNX(X_,0));
DYNX(DYNhelp,70) = tanh(0.5*DYNX(DYNhelp,69));
DYNX(W_,14) = DYNX(W_,45)+DYNX(Y_,1)+DYNX(W_,48)+DYNX(W_,47)+DYNX(W_,49)*
  DYNX(DYNhelp,68)*DYNX(DYNhelp,70);
 /* Linear system of equations to solve. */
DYNX(Y_,4) = RememberSimple_(DYNX(Y_,4), 0);
SolveScalarLinearParametric(DYNX(DP_,88),"chassis.m", DYNX(W_,14),"trans.Fx", 
  DYNX(Y_,4),"ax");
 /* End of Equation Block */ 

DYNX(Y_,5) = DYNX(DYNhelp,54)*DYNX(W_,57)+DYNX(DYNhelp,53)*DYNX(W_,58);
DYNX(Y_,7) = IF Greater(DYNX(Y_,4),"ax", 0,"0", 0) THEN 0 ELSE DYNX(Y_,4);
 /* Linear system of equations to solve. */
DYNX(Y_,9) = RememberSimple_(DYNX(Y_,9), 1);
SolveScalarLinearParametric(DYNX(DP_,88),"chassis.m", DYNX(Y_,5)+DYNX(W_,46),
  "Fyf+chassis.Fyr", DYNX(Y_,9),"ay");
 /* End of Equation Block */ 


DynamicsSection
DYNX(W_,50) = 0.01*DYNX(U_,1)*DYNX(DP_,95);
 /* Linear system of equations to solve. */
/* Introducing 3 common subexpressions used in 0 expressions */
/* Of the common subexpressions 3 are reals, 0 are integers, and 0
   are booleans. */
DYNX(DYNhelp,71) = tanh(10*DYNX(X_,7));
DYNX(DYNhelp,72) = fabs(DYNX(W_,54));
DYNX(DYNhelp,73) = tanh(0.5*DYNX(DYNhelp,72));
DYNX(F_,7) = RememberSimple_(DYNX(F_,7), 2);
SolveScalarLinearParametric(DYNX(DP_,111),"wheel1.I_tyre",  -(DYNX(DYNhelp,71)*
  DYNX(DYNhelp,73)*DYNX(W_,50)+DYNX(W_,57)*DYNX(DP_,107))," -(tanh(10*wheel1.omega)*tanh(0.5*abs(wheel1.vx))*chassis.Tbw+wheel1.Fxw*wheel1.rw)",
   DYNX(F_,7),"der(wheel1.omega)");
 /* End of Equation Block */ 

DYNX(F_,0) = DYNX(Y_,4)+DYNX(X_,2)*DYNX(X_,4);
DYNX(W_,39) = IF Greater(DYNX(U_,4),"r_gear", 0,"0", 1) THEN 1 ELSE 0;
DYNX(W_,34) = 0.5*(DYNX(X_,7)+DYNX(X_,8));
 /* Linear system of equations to solve. */
/* Introducing 1 common subexpressions used in 1 expressions */
/* Of the common subexpressions 1 are reals, 0 are integers, and 0
   are booleans. */
DYNX(DYNhelp,74) = divmacro(1.0,"1.0",DYNX(DP_,60),"trans.i_final");
DYNX(W_,32) = RememberSimple_(DYNX(W_,32), 3);
SolveScalarLinearParametric(DYNX(DYNhelp,74),"1.0/trans.i_final", DYNX(W_,34),
  "trans.w_w", DYNX(W_,32),"trans.w_p");
 /* End of Equation Block */ 

 /* Linear system of equations to solve. */
/* Introducing 1 common subexpressions used in 1 expressions */
/* Of the common subexpressions 1 are reals, 0 are integers, and 0
   are booleans. */
DYNX(DYNhelp,75) = divmacro(1.0,"1.0",RealElement( RealTemporaryDense( 
  &DYNX(DP_,48), 1, 12), (SizeType)(DYNX(W_,25))),"trans.i_tm[trans.agear]");
PopAllMarks();
DYNX(W_,30) = RememberSimple_(DYNX(W_,30), 4);
SolveScalarLinear(DYNX(DYNhelp,75),"1.0/trans.i_tm[trans.agear]", DYNX(W_,32),
  "trans.w_p", DYNX(W_,30),"trans.w_c");
 /* End of Equation Block */ 

DYNX(DYNhelp,76) = RealBmin(0.01*DYNX(U_,0), 1);
DYNX(W_,5) = RealBmax(DYNX(DYNhelp,76), 0.0);
DYNX(DYNhelp,77) = RealBmax(DYNX(W_,30), 62.83185307179586);
DYNX(W_,15) = RealBmin(209.43951023931953, DYNX(DYNhelp,77));
DYNX(W_,8) = (PushModelContext(1,"Modelica.Blocks.Tables.CombiTable1Ds.getTableValue(\ntrans.tab_torque.tableID, \n1, \ntrans.w_engine, \ntrans.tab_torque.tableOnFileRead)")
  Modelica_Blocks_Tables_CombiTable1Ds_getTableValue_M(DymStruc0_construct(
  (Integer)(DYNX(W_,22))), 1, DYNX(W_,15), DYNX(W_,23)));
PopModelContext();
DYNX(W_,9) = IF Greater(DYNX(F_,0),"der(trans.Vx)", DYNX(DP_,8),"trans.axh", 2)
   THEN DYNX(DP_,10)*DYNX(W_,8) ELSE IF Less(DYNX(F_,0),"der(trans.Vx)", 
  DYNX(DP_,9),"trans.axl", 3) THEN DYNX(W_,8) ELSE DYNX(W_,8)*(1+divmacro((
  DYNX(F_,0)-DYNX(DP_,9))*(DYNX(DP_,10)-1),"(der(trans.Vx)-trans.axl)*(trans.E_factor-1)",
  DYNX(DP_,8)-DYNX(DP_,9),"trans.axh-trans.axl"));
DYNX(DYNhelp,78) = tanh(0.01*(DYNX(W_,15)-209.43951023931953));
DYNX(W_,6) = DYNX(W_,5)*DYNX(W_,9)*(1-DYNX(DYNhelp,78))*DYNX(W_,4);
DYNX(W_,11) = RealBmin(DYNX(W_,6), DYNX(DP_,11));
DYNX(W_,13) = DYNX(W_,11)+DYNX(X_,1);
DYNX(W_,7) = IF DYNX(X_,0) < 0 THEN RealBmax(0, DYNX(W_,13)) ELSE DYNX(W_,13);

{ /* Non-linear system of equations to solve. */
  /* Nonlinear system of equations number = 2. */
/* Introducing 31 common subexpressions and reusing 1 variables totally used in 7
   expressions */
/* Of the common subexpressions 28 are reals, 0 are integers, and 4
   are booleans. */
const char*const varnames_[]={"wheel2.der(omega)"};
const double nominal_[]={1};
NonLinearSystemOfEquationsNH(Jacobian__, residue__, x__, 1, 0, 2, 9, 10, 
  DYNX(DYNhelp,79), 55, DYNX(did_->helpvari_vec,23), 23);
NonLinearSystemSave(DYNX(Y_,1), 0);
NonLinearSystemSave(DYNX(W_,50), 1);
NonLinearSystemSave(DYNX(F_,7), 2);
NonLinearSystemSave(DYNX(U_,4), 3);
NonLinearSystemSave(DYNX(W_,7), 4);
NonLinearSystemSave(DYNX(X_,0), 5);
NonLinearSystemSave(DYNX(W_,25), 6);
NonLinearSystemSave(DYNX(W_,39), 7);
NonLinearSystemSave(DYNX(W_,30), 8);
NonLinearSystemSave(DYNX(X_,8), 9);
SetInitVectorNH(x__, 1, DYNX(F_,8), Remember_(DYNX(F_,8), 5));
Residues;
  DYNX(W_,35) = 0.5*(DYNX(F_,7)+DYNX(F_,8));
  DYNX(W_,33) = DYNX(W_,35)*DYNX(DP_,60);
  DYNX(DYNhelp,134) = RealElement( RealTemporaryDense( &DYNX(DP_,48), 1, 12), 
    (SizeType)(DYNX(W_,25)));
  PopAllMarks();
  DYNX(W_,31) = DYNX(W_,33)*DYNX(DYNhelp,134);
  DYNX(DYNhelp,135) = 209.43951023931953 < DYNX(DYNhelp,77);
  DYNX(W_,16) = IF DYNX(DYNhelp,135) THEN 0.0 ELSE IF DYNX(W_,30) > 
    62.83185307179586 THEN DYNX(W_,31) ELSE 0.0;
  DYNX(W_,27) = DYNX(W_,7)-DYNX(DP_,106)*DYNX(W_,16);
  DYNX(W_,28) = DYNX(W_,27)*DYNX(DYNhelp,134);
  DYNX(W_,29) = DYNX(DP_,61)*DYNX(W_,28)*DYNX(DP_,60);
  DYNX(W_,37) = RealBmax(DYNX(W_,29), 0);
  DYNX(DYNhelp,136) = 1*DYNX(W_,39);
  DYNX(DYNhelp,137) = RealBmax(DYNX(W_,27), 0);
  DYNX(W_,38) =  -DYNX(DYNhelp,136)*DYNX(DYNhelp,137)*DYNX(DP_,53)*DYNX(DP_,60);
  DYNX(DYNhelp,138) = Equal(DYNX(U_,4), 1, 4);
  DYNX(W_,70) = IF DYNX(DYNhelp,138) THEN DYNX(W_,38) ELSE DYNX(W_,37);
DYNX(DYNhelp,139) = tanh(10*DYNX(X_,8));
SetVector(residue__, 1, DYNX(DP_,116)*DYNX(F_,8)-DYNX(W_,70)+DYNX(DYNhelp,139)*
  DYNX(DYNhelp,70)*DYNX(W_,50)+DYNX(Y_,1)*DYNX(DP_,112));

Jacobian(Jacobian__)
MatrixZeros(Jacobian__);
DYNX(DYNhelp,140) = DYNX(W_,27) > 0;
DYNX(DYNhelp,141) = DYNX(DP_,106)*(DYNX(DYNhelp,134)*DYNX(DP_,60)*DYNX(DP_,61)*(
  IF DYNX(W_,29) > 0 THEN 1.0 ELSE 0.0)*(IF DYNX(DYNhelp,138) THEN 0.0 ELSE 1.0)
  -DYNX(DP_,60)*DYNX(DP_,53)*DYNX(DYNhelp,136)*(IF DYNX(DYNhelp,140) THEN 1.0
   ELSE 0.0)*(IF DYNX(DYNhelp,138) THEN 1.0 ELSE 0.0));
SetMatrixLeading(Jacobian__, 1, 1, 1, DYNX(DP_,116)+0.5*DYNX(DP_,60)*
  DYNX(DYNhelp,134)*(IF DYNX(DYNhelp,135) THEN 0.0 ELSE IF DYNX(W_,30) > 
  62.83185307179586 THEN 1.0 ELSE 0.0)*DYNX(DYNhelp,141));

SolveNonLinearSystemOfEquationsNH(Jacobian__, residue__, x__, 2);
DYNX(F_,8) = GetVector(x__, 1);
EndNonLinearSystemOfEquationsNH(residue__, x__, 2);
 /* End of Non-Linear Equation Block */ }



DYNX(W_,12) = DYNX(W_,6)-DYNX(W_,11);
DYNX(F_,1) = DYNX(DP_,12)*(DYNX(W_,12)-DYNX(X_,1));
 /* Linear system of equations to solve. */
DYNX(F_,4) = RememberSimple_(DYNX(F_,4), 6);
SolveScalarLinearParametric(DYNX(DP_,91),"chassis.Izz", DYNX(DP_,89)*DYNX(Y_,5)-
  DYNX(DP_,90)*DYNX(W_,46),"chassis.a*Fyf-chassis.b*chassis.Fyr", DYNX(F_,4),
  "der(chassis.yaw_velocity)");
 /* End of Equation Block */ 

DYNX(F_,2) = DYNX(Y_,9)-DYNX(X_,0)*DYNX(X_,4);
DYNX(F_,3) = DYNX(X_,4);
DYNX(DYNhelp,142) = cos(DYNX(X_,3));
DYNX(DYNhelp,143) = sin(DYNX(X_,3));
DYNX(F_,5) = DYNX(X_,0)*DYNX(DYNhelp,142)-DYNX(X_,2)*DYNX(DYNhelp,143);
DYNX(F_,6) = DYNX(X_,2)*DYNX(DYNhelp,142)+DYNX(X_,0)*DYNX(DYNhelp,143);

AcceptedSection1

AcceptedSection2
DYNX(W_,17) = 0.3183098861837907*DYNX(W_,15)*30;
DYNX(W_,10) = DYNX(DP_,4)*powmacro(DYNX(W_,17),"trans.rpm_engine",3,"3")+
  DYNX(DP_,5)*sqr(DYNX(W_,17))+DYNX(DP_,6)*DYNX(W_,17)+DYNX(DP_,7);
DYNX(W_,26) = DYNX(DP_,60)*RealElement( RealTemporaryDense( &DYNX(DP_,48), 1, 12),
   (SizeType)(DYNX(W_,25)));
PopAllMarks();

DefaultSection
InitializeData(1)
EndTranslatedEquations

#include <dsblock6.c>

PreNonAliasNew(0)
StartNonAlias(0)
DeclareVariable("trans.pi", "", 3.141592653589793, 0.0,0.0,0.0,0,513)
DeclareVariable("trans.m", "[kg]", 0.0, 0.0,1E+100,0.0,0,513)
DeclareParameter("trans.k3max", "", 0, -1.246E-006, 0.0,0.0,0.0,0,560)
DeclareParameter("trans.k2max", "", 1, 0.0001471, 0.0,0.0,0.0,0,560)
DeclareParameter("trans.k1max", "", 2, 6.511, 0.0,0.0,0.0,0,560)
DeclareParameter("trans.k0max", "", 3, -2228.7, 0.0,0.0,0.0,0,560)
DeclareParameter("trans.k3min", "[J.s3.rad-3]", 4, -1.59E-008, 0.0,0.0,0.0,0,560)
DeclareParameter("trans.k2min", "[J.s2.rad-2]", 5, 8.752E-005, 0.0,0.0,0.0,0,560)
DeclareParameter("trans.k1min", "[J.s.rad-1]", 6, -0.197569, 0.0,0.0,0.0,0,560)
DeclareParameter("trans.k0min", "[N.m]", 7, -4.22681, 0.0,0.0,0.0,0,560)
DeclareVariable("trans.w_eng_max", "maximum engine rotation [rad/s]", \
209.43951023931953, 0.0,0.0,0.0,0,513)
DeclareVariable("trans.w_eng_idl", " engine idle speed [rad/s]", \
62.83185307179586, 0.0,0.0,0.0,0,513)
DeclareParameter("trans.axh", "Upper acceleration limit [m/s2]", 8, 0.7, \
0.0,0.0,0.0,0,560)
DeclareParameter("trans.axl", "Lower acceleration limit [m/s2]", 9, 0.6, \
0.0,0.0,0.0,0,560)
DeclareParameter("trans.E_factor", "[1]", 10, 0.45, 0.0,0.0,0.0,0,560)
DeclareParameter("trans.Tsplit", "[N.m]", 11, 700, 0.0,0.0,0.0,0,560)
DeclareParameter("trans.k", "Boost pressure coefficient [s-1]", 12, 1, 0.0,0.0,\
0.0,0,560)
DeclareVariable("trans.hf", "", 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("trans.perc_throttle", "", 0.0, 0.0,0.0,0.0,0,512)
DeclareAlias2("trans.Aped", "Accelerator pedal position [%] []", "Aped", 1, 2, 0,\
 0)
DeclareState("trans.Vx", "velocity of the vehicle m/s [m/s]", 0, 0.0, 0.0,0.0,\
0.0,0,544)
DeclareDerivative("trans.der(Vx)", "der(velocity of the vehicle m/s) [m/s2]", \
0.0, 0.0,0.0,0.0,0,512)
DeclareVariable("trans.torque", "engine torque [N.m]", 0, 0.0,0.0,0.0,0,512)
DeclareVariable("trans.Te", "[N.m]", 0.0, 0.0,0.0,0.0,0,512)
DeclareVariable("trans.max_torque", "[N.m]", 0.0, 0.0,0.0,0.0,0,512)
DeclareVariable("trans.max_torque_alim", "[N.m]", 0.0, 0.0,0.0,0.0,0,512)
DeclareVariable("trans.min_torque", "[N.m]", 0.0, 0.0,0.0,0.0,0,512)
DeclareVariable("trans.Tbase", "[N.m]", 0.0, 0.0,0.0,0.0,0,512)
DeclareVariable("trans.Tdynreq", "[N.m]", 0.0, 0.0,0.0,0.0,0,512)
DeclareState("trans.Ttop", "[N.m]", 1, 0.0, 0.0,0.0,0.0,0,560)
DeclareDerivative("trans.der(Ttop)", "[W]", 0.0, 0.0,0.0,0.0,0,512)
DeclareVariable("trans.T_e", "[N.m]", 0.0, 0.0,0.0,0.0,0,512)
DeclareVariable("trans.Fx", "Force to compute ax [N]", 0.0, 0.0,0.0,0.0,0,512)
DeclareVariable("trans.w_engine", "engine speed in rad/s [rad/s]", \
62.83185307179586, 0.0,0.0,0.0,0,512)
DeclareVariable("trans.der(w_engine)", "der(engine speed in rad/s) [rad/s2]", \
0.0, 0.0,0.0,0.0,0,512)
DeclareVariable("trans.rpm_engine", "engine speed in rpm [rad/s]", 0.0, 0.0,0.0,\
0.0,0,512)
DeclareVariable("trans.tab_torque.nout", "Number of outputs [:#(type=Integer)]",\
 1, 0.0,0.0,0.0,0,517)
DeclareAlias2("trans.tab_torque.u", "Connector of Real input signal [rad/s]", \
"trans.w_engine", 1, 5, 15, 0)
DeclareAlias2("trans.tab_torque.y[1]", "Connector of Real output signals", \
"trans.max_torque", 1, 5, 8, 0)
DeclareVariable("trans.tab_torque.tableOnFile", "= true, if table is defined on file or in function usertab [:#(type=Boolean)]",\
 false, 0.0,0.0,0.0,0,515)
DeclareParameter("trans.tab_torque.table[1, 1]", "Table matrix (grid = first column; e.g., table=[0,2])",\
 13, 0, 0.0,0.0,0.0,0,560)
DeclareParameter("trans.tab_torque.table[1, 2]", "Table matrix (grid = first column; e.g., table=[0,2])",\
 14, 0, 0.0,0.0,0.0,0,560)
DeclareParameter("trans.tab_torque.table[2, 1]", "Table matrix (grid = first column; e.g., table=[0,2])",\
 15, 62.8318, 0.0,0.0,0.0,0,560)
DeclareParameter("trans.tab_torque.table[2, 2]", "Table matrix (grid = first column; e.g., table=[0,2])",\
 16, 1660.0, 0.0,0.0,0.0,0,560)
DeclareParameter("trans.tab_torque.table[3, 1]", "Table matrix (grid = first column; e.g., table=[0,2])",\
 17, 73.3038, 0.0,0.0,0.0,0,560)
DeclareParameter("trans.tab_torque.table[3, 2]", "Table matrix (grid = first column; e.g., table=[0,2])",\
 18, 1880.0, 0.0,0.0,0.0,0,560)
DeclareParameter("trans.tab_torque.table[4, 1]", "Table matrix (grid = first column; e.g., table=[0,2])",\
 19, 83.775, 0.0,0.0,0.0,0,560)
DeclareParameter("trans.tab_torque.table[4, 2]", "Table matrix (grid = first column; e.g., table=[0,2])",\
 20, 2240.0, 0.0,0.0,0.0,0,560)
DeclareParameter("trans.tab_torque.table[5, 1]", "Table matrix (grid = first column; e.g., table=[0,2])",\
 21, 94.247, 0.0,0.0,0.0,0,560)
DeclareParameter("trans.tab_torque.table[5, 2]", "Table matrix (grid = first column; e.g., table=[0,2])",\
 22, 2900.0, 0.0,0.0,0.0,0,560)
DeclareParameter("trans.tab_torque.table[6, 1]", "Table matrix (grid = first column; e.g., table=[0,2])",\
 23, 104.719, 0.0,0.0,0.0,0,560)
DeclareParameter("trans.tab_torque.table[6, 2]", "Table matrix (grid = first column; e.g., table=[0,2])",\
 24, 3550.0, 0.0,0.0,0.0,0,560)
DeclareParameter("trans.tab_torque.table[7, 1]", "Table matrix (grid = first column; e.g., table=[0,2])",\
 25, 115.191, 0.0,0.0,0.0,0,560)
DeclareParameter("trans.tab_torque.table[7, 2]", "Table matrix (grid = first column; e.g., table=[0,2])",\
 26, 3550.0, 0.0,0.0,0.0,0,560)
DeclareParameter("trans.tab_torque.table[8, 1]", "Table matrix (grid = first column; e.g., table=[0,2])",\
 27, 125.663, 0.0,0.0,0.0,0,560)
DeclareParameter("trans.tab_torque.table[8, 2]", "Table matrix (grid = first column; e.g., table=[0,2])",\
 28, 3550.0, 0.0,0.0,0.0,0,560)
DeclareParameter("trans.tab_torque.table[9, 1]", "Table matrix (grid = first column; e.g., table=[0,2])",\
 29, 136.135, 0.0,0.0,0.0,0,560)
DeclareParameter("trans.tab_torque.table[9, 2]", "Table matrix (grid = first column; e.g., table=[0,2])",\
 30, 3550.0, 0.0,0.0,0.0,0,560)
DeclareParameter("trans.tab_torque.table[10, 1]", "Table matrix (grid = first column; e.g., table=[0,2])",\
 31, 146.607, 0.0,0.0,0.0,0,560)
DeclareParameter("trans.tab_torque.table[10, 2]", "Table matrix (grid = first column; e.g., table=[0,2])",\
 32, 3550.0, 0.0,0.0,0.0,0,560)
DeclareParameter("trans.tab_torque.table[11, 1]", "Table matrix (grid = first column; e.g., table=[0,2])",\
 33, 157.079, 0.0,0.0,0.0,0,560)
DeclareParameter("trans.tab_torque.table[11, 2]", "Table matrix (grid = first column; e.g., table=[0,2])",\
 34, 3470.0, 0.0,0.0,0.0,0,560)
DeclareParameter("trans.tab_torque.table[12, 1]", "Table matrix (grid = first column; e.g., table=[0,2])",\
 35, 167.551, 0.0,0.0,0.0,0,560)
DeclareParameter("trans.tab_torque.table[12, 2]", "Table matrix (grid = first column; e.g., table=[0,2])",\
 36, 3310.0, 0.0,0.0,0.0,0,560)
DeclareParameter("trans.tab_torque.table[13, 1]", "Table matrix (grid = first column; e.g., table=[0,2])",\
 37, 178.023, 0.0,0.0,0.0,0,560)
DeclareParameter("trans.tab_torque.table[13, 2]", "Table matrix (grid = first column; e.g., table=[0,2])",\
 38, 3120.0, 0.0,0.0,0.0,0,560)
DeclareParameter("trans.tab_torque.table[14, 1]", "Table matrix (grid = first column; e.g., table=[0,2])",\
 39, 188.495, 0.0,0.0,0.0,0,560)
DeclareParameter("trans.tab_torque.table[14, 2]", "Table matrix (grid = first column; e.g., table=[0,2])",\
 40, 2880.0, 0.0,0.0,0.0,0,560)
DeclareParameter("trans.tab_torque.table[15, 1]", "Table matrix (grid = first column; e.g., table=[0,2])",\
 41, 198.967, 0.0,0.0,0.0,0,560)
DeclareParameter("trans.tab_torque.table[15, 2]", "Table matrix (grid = first column; e.g., table=[0,2])",\
 42, 2660.0, 0.0,0.0,0.0,0,560)
DeclareParameter("trans.tab_torque.table[16, 1]", "Table matrix (grid = first column; e.g., table=[0,2])",\
 43, 209.439, 0.0,0.0,0.0,0,560)
DeclareParameter("trans.tab_torque.table[16, 2]", "Table matrix (grid = first column; e.g., table=[0,2])",\
 44, 1680.0, 0.0,0.0,0.0,0,560)
DeclareParameter("trans.tab_torque.table[17, 1]", "Table matrix (grid = first column; e.g., table=[0,2])",\
 45, 219.911, 0.0,0.0,0.0,0,560)
DeclareParameter("trans.tab_torque.table[17, 2]", "Table matrix (grid = first column; e.g., table=[0,2])",\
 46, 0.0, 0.0,0.0,0.0,0,560)
DeclareParameter("trans.tab_torque.verboseRead", "= true, if info message that file is loading is to be printed [:#(type=Boolean)]",\
 47, true, 0.0,0.0,0.0,0,562)
DeclareVariable("trans.tab_torque.columns[1]", "Columns of table to be interpolated [:#(type=Integer)]",\
 2, 0.0,0.0,0.0,0,517)
DeclareVariable("trans.tab_torque.smoothness", "Smoothness of table interpolation [:#(type=Modelica.Blocks.Types.Smoothness)]",\
 1, 1.0,5.0,0.0,0,517)
DeclareVariable("trans.tab_torque.tableID.id", "[:#(type=Integer)]", 0, 0.0,0.0,\
0.0,0,2565)
DeclareVariable("trans.tab_torque.tableOnFileRead", "= 1, if table was successfully read from file",\
 0.0, 0.0,0.0,0.0,0,2561)
DeclareParameter("trans.i_tm[1]", "gear ratios from 1st up to 12th gear", 48, \
14.356, 0.0,0.0,0.0,0,560)
DeclareParameter("trans.i_tm[2]", "gear ratios from 1st up to 12th gear", 49, \
11.7239, 0.0,0.0,0.0,0,560)
DeclareParameter("trans.i_tm[3]", "gear ratios from 1st up to 12th gear", 50, \
9.0363, 0.0,0.0,0.0,0,560)
DeclareParameter("trans.i_tm[4]", "gear ratios from 1st up to 12th gear", 51, \
7.0941, 0.0,0.0,0.0,0,560)
DeclareParameter("trans.i_tm[5]", "gear ratios from 1st up to 12th gear", 52, \
5.5382, 0.0,0.0,0.0,0,560)
DeclareParameter("trans.i_tm[6]", "gear ratios from 1st up to 12th gear", 53, \
4.3478, 0.0,0.0,0.0,0,560)
DeclareParameter("trans.i_tm[7]", "gear ratios from 1st up to 12th gear", 54, \
3.4363, 0.0,0.0,0.0,0,560)
DeclareParameter("trans.i_tm[8]", "gear ratios from 1st up to 12th gear", 55, \
2.6977, 0.0,0.0,0.0,0,560)
DeclareParameter("trans.i_tm[9]", "gear ratios from 1st up to 12th gear", 56, \
2.0783, 0.0,0.0,0.0,0,560)
DeclareParameter("trans.i_tm[10]", "gear ratios from 1st up to 12th gear", 57, \
1.6316, 0.0,0.0,0.0,0,560)
DeclareParameter("trans.i_tm[11]", "gear ratios from 1st up to 12th gear", 58, \
1.2738, 0.0,0.0,0.0,0,560)
DeclareParameter("trans.i_tm[12]", "gear ratios from 1st up to 12th gear", 59, \
1.0, 0.0,0.0,0.0,0,560)
DeclareParameter("trans.i_final", "gear ratio final gear [1]", 60, 3.46, \
0.0,0.0,0.0,0,560)
DeclareParameter("trans.eff_tr", "transmission efficiency", 61, 0.9, 0.0,0.0,0.0,\
0,560)
DeclareParameter("trans.upshift[1]", "", 62, 2.31, 0.0,0.0,0.0,0,560)
DeclareParameter("trans.upshift[2]", "", 63, 3.0, 0.0,0.0,0.0,0,560)
DeclareParameter("trans.upshift[3]", "", 64, 3.81, 0.0,0.0,0.0,0,560)
DeclareParameter("trans.upshift[4]", "", 65, 4.86, 0.0,0.0,0.0,0,560)
DeclareParameter("trans.upshift[5]", "", 66, 6.25, 0.0,0.0,0.0,0,560)
DeclareParameter("trans.upshift[6]", "", 67, 8.0, 0.0,0.0,0.0,0,560)
DeclareParameter("trans.upshift[7]", "", 68, 10.02, 0.0,0.0,0.0,0,560)
DeclareParameter("trans.upshift[8]", "", 69, 12.8, 0.0,0.0,0.0,0,560)
DeclareParameter("trans.upshift[9]", "", 70, 16.65, 0.0,0.0,0.0,0,560)
DeclareParameter("trans.upshift[10]", "", 71, 21.2, 0.0,0.0,0.0,0,560)
DeclareParameter("trans.upshift[11]", "", 72, 27.1, 0.0,0.0,0.0,0,560)
DeclareParameter("trans.upshift[12]", "", 73, 1000000.0, 0.0,0.0,0.0,0,560)
DeclareParameter("trans.downshift[1]", "", 74, -1000000.0, 0.0,0.0,0.0,0,560)
DeclareParameter("trans.downshift[2]", "", 75, 2.2, 0.0,0.0,0.0,0,560)
DeclareParameter("trans.downshift[3]", "", 76, 2.28, 0.0,0.0,0.0,0,560)
DeclareParameter("trans.downshift[4]", "", 77, 3.5, 0.0,0.0,0.0,0,560)
DeclareParameter("trans.downshift[5]", "", 78, 4.5, 0.0,0.0,0.0,0,560)
DeclareParameter("trans.downshift[6]", "", 79, 6.0, 0.0,0.0,0.0,0,560)
DeclareParameter("trans.downshift[7]", "", 80, 7.5, 0.0,0.0,0.0,0,560)
DeclareParameter("trans.downshift[8]", "", 81, 9.4, 0.0,0.0,0.0,0,560)
DeclareParameter("trans.downshift[9]", "", 82, 12.0, 0.0,0.0,0.0,0,560)
DeclareParameter("trans.downshift[10]", "", 83, 15.5, 0.0,0.0,0.0,0,560)
DeclareParameter("trans.downshift[11]", "", 84, 20.0, 0.0,0.0,0.0,0,560)
DeclareParameter("trans.downshift[12]", "", 85, 25.0, 0.0,0.0,0.0,0,560)
DeclareParameter("trans.max_drive_torque", "[N.m]", 86, 1200000.0, 0.0,0.0,0.0,0,560)
DeclareParameter("trans.dds", "damping factor for drive shaft flexibility ", 87,\
 5, 0.0,0.0,0.0,0,560)
DeclareVariable("trans.st_agear", "[:#(type=Integer)]", 0, 0.0,0.0,0.0,0,517)
DeclareVariable("trans.agear", " the automatic gear [:#(type=Integer)]", 0, \
0.0,0.0,0.0,0,644)
DeclareVariable("trans.i_T", "total transmission ratio", 0, 0.0,0.0,0.0,0,640)
DeclareAlias2("trans.r_gear", "", "r_gear", 1, 2, 4, 0)
DeclareAlias2("trans.Je", "[J.s2.rad-1]", "chassis.Je", 1, 7, 106, 0)
DeclareVariable("trans.Tc", "[N.m]", 0.0, 0.0,0.0,0.0,0,512)
DeclareAlias2("trans.Tt", "[N.m]", "trans.Tc", 1, 5, 27, 0)
DeclareVariable("trans.Tp", "[N.m]", 0.0, 0.0,0.0,0.0,0,512)
DeclareAlias2("trans.Tf", "[N.m]", "trans.Tp", 1, 5, 28, 0)
DeclareVariable("trans.Td", "[N.m]", 0.0, 0.0,0.0,0.0,0,512)
DeclareAlias2("trans.Tw", "[N.m]", "trans.Td", 1, 5, 29, 0)
DeclareVariable("trans.w_c", "[rad/s]", 0.0, 0.0,0.0,0.0,0,512)
DeclareVariable("trans.der(w_c)", "[rad/s2]", 0.0, 0.0,0.0,0.0,0,512)
DeclareAlias2("trans.w_t", "[rad/s]", "trans.w_c", 1, 5, 30, 0)
DeclareVariable("trans.w_p", "[rad/s]", 0.0, 0.0,0.0,0.0,0,512)
DeclareVariable("trans.der(w_p)", "[rad/s2]", 0.0, 0.0,0.0,0.0,0,512)
DeclareAlias2("trans.w_f", "[rad/s]", "trans.w_p", 1, 5, 32, 0)
DeclareVariable("trans.w_w", "[rad/s]", 0.0, 0.0,0.0,0.0,0,512)
DeclareVariable("trans.der(w_w)", "[rad/s2]", 0.0, 0.0,0.0,0.0,0,512)
DeclareVariable("trans.M_wheel_1", "[N.m]", 0, 0.0,0.0,0.0,0,513)
DeclareVariable("trans.M_wheel_2", "[N.m]", 0.0, 0.0,0.0,0.0,0,512)
DeclareAlias2("trans.w_wheel_1", "[rad/s]", "wheel1.omega", 1, 1, 7, 0)
DeclareAlias2("trans.w_wheel_2", "[rad/s]", "wheel2.omega", 1, 1, 8, 0)
DeclareAlias2("trans.w_mean_wheels", "[rad/s]", "trans.w_w", 1, 5, 34, 0)
DeclareVariable("trans.rev_torque", "[N.m]", 0.0, 0.0,0.0,0.0,0,512)
DeclareVariable("trans.r_c", "", 0.0, 0.0,0.0,0.0,0,640)
DeclareVariable("chassis.g", "", 9.80665, 0.0,0.0,0.0,0,513)
DeclareParameter("chassis.m", "[kg]", 88, 9481, 0.0,0.0,0.0,0,560)
DeclareParameter("chassis.a", "[m]", 89, 1.68, 0.0,0.0,0.0,0,560)
DeclareParameter("chassis.b", "[m]", 90, 1.715, 0.0,0.0,0.0,0,560)
DeclareParameter("chassis.Izz", "[m2.kg]", 91, 41340, 0.0,0.0,0.0,0,560)
DeclareParameter("chassis.i_s", "", 92, 16, 0.0,0.0,0.0,0,560)
DeclareParameter("chassis.Iw", "", 93, 1, 0.0,0.0,0.0,0,560)
DeclareParameter("chassis.rw", "", 94, 0.5, 0.0,0.0,0.0,0,560)
DeclareParameter("chassis.Tb", "", 95, 25000, 0.0,0.0,0.0,0,560)
DeclareVariable("chassis.m_f", "[kg]", 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("chassis.m_r", "[kg]", 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("chassis.Fzf", "[N]", 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("chassis.Fzr", "[N]", 0.0, 0.0,0.0,0.0,0,513)
DeclareParameter("chassis.vx0", "[m/s]", 96, 0.0, 0.0,0.0,0.0,0,560)
DeclareParameter("chassis.Fxmax", "", 97, 3000000, 0.0,0.0,0.0,0,560)
DeclareParameter("chassis.Pmax", "", 98, 29000, 0.0,0.0,0.0,0,560)
DeclareParameter("chassis.f_r", "Rolling resistance coefficient", 99, 0.0164, \
0.0,0.0,0.0,0,560)
DeclareParameter("chassis.rho", "air density", 100, 1.225, 0.0,0.0,0.0,0,560)
DeclareParameter("chassis.Cd", "", 101, 0.7, 0.0,0.0,0.0,0,560)
DeclareParameter("chassis.ac", "", 102, 10, 0.0,0.0,0.0,0,560)
DeclareParameter("chassis.cx", "", 103, 20, 0.0,0.0,0.0,0,560)
DeclareParameter("chassis.mu", "", 104, 0.9, 0.0,0.0,0.0,0,560)
DeclareParameter("chassis.ratio", "", 105, 3.0, 0.0,0.0,0.0,0,560)
DeclareParameter("chassis.Je", "Engine inertia [J.s2.rad-1]", 106, 3, 0.0,0.0,\
0.0,0,560)
DeclareState("chassis.vy", "Vehicle Lateral Velocity [m/sec] [m/s]", 2, 0.0, \
0.0,0.0,0.0,0,560)
DeclareDerivative("chassis.der(vy)", "der(Vehicle Lateral Velocity [m/sec]) [m/s2]",\
 0.0, 0.0,0.0,0.0,0,512)
DeclareState("chassis.yaw_angle", "[1]", 3, 0, 0.0,0.0,0.0,0,560)
DeclareDerivative("chassis.der(yaw_angle)", "[s-1]", 0.0, 0.0,0.0,0.0,0,512)
DeclareState("chassis.yaw_velocity", "[s-1]", 4, 0, 0.0,0.0,0.0,0,560)
DeclareDerivative("chassis.der(yaw_velocity)", "[s-2]", 0.0, 0.0,0.0,0.0,0,512)
DeclareAlias2("chassis.ay", "[m/s2]", "ay", 1, 3, 9, 0)
DeclareAlias2("chassis.Fx", "[N]", "trans.Fx", 1, 5, 14, 0)
DeclareVariable("chassis.Fxf", "[N]", 0.0, 0.0,0.0,0.0,0,512)
DeclareVariable("chassis.Fyr", "[N]", 0.0, 0.0,0.0,0.0,0,512)
DeclareAlias2("chassis.Fxr", "[N]", "Fxr", 1, 3, 1, 0)
DeclareVariable("chassis.Fr", "[N]", 0.0, 0.0,0.0,0.0,0,512)
DeclareVariable("chassis.Fd", "[N]", 0.0, 0.0,0.0,0.0,0,512)
DeclareVariable("chassis.Fg", "", 0.0, 0.0,0.0,0.0,0,512)
DeclareVariable("chassis.Tbw", "[N.m]", 0.0, 0.0,0.0,0.0,0,512)
DeclareAlias2("chassis.delta", "[rad]", "delta", 1, 3, 6, 0)
DeclareVariable("chassis.womega", "", 0.0, 0.0,0.0,0.0,0,512)
DeclareAlias2("chassis.swa", "Steering angle [rad] []", "swa", 1, 2, 2, 0)
DeclareAlias2("chassis.brakeped", "[%] i/p of brake pedal", "Bped", 1, 2, 1, 0)
DeclareAlias2("chassis.theta", "", "theta", 1, 2, 3, 0)
DeclareAlias2("chassis.vx", "Vehicle longitudinal velocity [m/s]", "vx", 1, 3, 0,\
 0)
DeclareAlias2("chassis.der(vx)", "der(Vehicle longitudinal velocity) [m/s2]", \
"trans.der(Vx)", 1, 6, 0, 0)
DeclareState("chassis.x", "", 5, 0, 0.0,0.0,0.0,0,560)
DeclareDerivative("chassis.der(x)", "", 0.0, 0.0,0.0,0.0,0,512)
DeclareState("chassis.y", "", 6, 0, 0.0,0.0,0.0,0,560)
DeclareDerivative("chassis.der(y)", "", 0.0, 0.0,0.0,0.0,0,512)
DeclareAlias2("chassis.ax", "[m/s2]", "ax", 1, 3, 4, 0)
DeclareAlias2("chassis.Fyf", "[N]", "Fyf", 1, 3, 5, 0)
DeclareAlias2("chassis.decl", "[m/s2]", "decl", 1, 3, 7, 0)
DeclareVariable("wheel1.pi", "", 3.141592653589793, 0.0,0.0,0.0,0,513)
DeclareParameter("wheel1.rw", "Radius of wheel [m/rad]", 107, 0.5, 0.0,0.0,0.0,0,560)
DeclareParameter("wheel1.c", "", 108, 20, 0.0,0.0,0.0,0,560)
DeclareParameter("wheel1.mu", "", 109, 0.9, 0.0,0.0,0.0,0,560)
DeclareParameter("wheel1.vx0", "[m/s]", 110, 0, 0.0,0.0,0.0,0,560)
DeclareParameter("wheel1.I_tyre", "[J.s2.rad-1]", 111, 11, 0.0,0.0,0.0,0,560)
DeclareAlias2("wheel1.Vx", "Chassis long velocity [m/s]", "trans.Vx", 1, 1, 0, 0)
DeclareVariable("wheel1.Vy", "Chassis lat velocity [m/s]", 0.0, 0.0,0.0,0.0,0,512)
DeclareVariable("wheel1.vx", "wheel lon velocity [m/s]", 0.0, 0.0,0.0,0.0,0,512)
DeclareVariable("wheel1.vy", "wheel lat velcoity [m/s]", 0.0, 0.0,0.0,0.0,0,512)
DeclareState("wheel1.omega", "wheel angular velocity [rad/s]", 7, 0.0, 0.0,0.0,\
0.0,0,544)
DeclareDerivative("wheel1.der(omega)", "der(wheel angular velocity) [rad/s2]", \
0.0, 0.0,0.0,0.0,0,512)
DeclareVariable("wheel1.Fxy", "Tire Force combined [N]", 0.0, 0.0,0.0,0.0,0,512)
DeclareAlias2("wheel1.delta", "[rad|deg]", "delta", 1, 3, 6, 0)
DeclareAlias2("wheel1.Fz", "[N]", "chassis.Fzf", 1, 5, 43, 0)
DeclareVariable("wheel1.Fxw", "[N]", 0.0, 0.0,0.0,0.0,0,512)
DeclareVariable("wheel1.Fyw", "[N]", 0.0, 0.0,0.0,0.0,0,512)
DeclareAlias2("wheel1.Fxv", "[N]", "chassis.Fxf", 1, 5, 45, 0)
DeclareAlias2("wheel1.Fyv", "[N]", "Fyf", 1, 3, 5, 0)
DeclareVariable("wheel1.Drive_torque", "[N.m]", 0.0, 0.0,0.0,0.0,0,513)
DeclareAlias2("wheel1.Brake_torque", "[N.m]", "chassis.Tbw", 1, 5, 50, 0)
DeclareVariable("wheel1.sxy", "combined slip", 0.0, 0.0,0.0,0.0,0,512)
DeclareVariable("wheel1.fsxy", "tire coefficient", 0.0, 0.0,0.0,0.0,0,512)
DeclareVariable("wheel1.sx", "longitudinal slip [1]", 0.0, 0.0,0.0,0.0,0,512)
DeclareVariable("wheel1.sy", "Lateral slip [1]", 0.0, 0.0,0.0,0.0,0,512)
DeclareVariable("wheel1.Je", "Engine inertia", 0, 0.0,0.0,0.0,0,513)
DeclareVariable("wheel1.i_T", "gear and final drive ratio product", 0, 0.0,0.0,\
0.0,0,513)
DeclareVariable("wheel2.pi", "", 3.141592653589793, 0.0,0.0,0.0,0,513)
DeclareParameter("wheel2.rw", "Radius of wheel [m/rad]", 112, 0.5, 0.0,0.0,0.0,0,560)
DeclareParameter("wheel2.c", "", 113, 20, 0.0,0.0,0.0,0,560)
DeclareParameter("wheel2.mu", "", 114, 0.9, 0.0,0.0,0.0,0,560)
DeclareParameter("wheel2.vx0", "[m/s]", 115, 0, 0.0,0.0,0.0,0,560)
DeclareParameter("wheel2.I_tyre", "[J.s2.rad-1]", 116, 11, 0.0,0.0,0.0,0,560)
DeclareAlias2("wheel2.Vx", "Chassis long velocity [m/s]", "trans.Vx", 1, 1, 0, 0)
DeclareVariable("wheel2.Vy", "Chassis lat velocity [m/s]", 0.0, 0.0,0.0,0.0,0,512)
DeclareAlias2("wheel2.vx", "wheel lon velocity [m/s]", "trans.Vx", 1, 1, 0, 0)
DeclareAlias2("wheel2.vy", "wheel lat velcoity [m/s]", "wheel2.Vy", 1, 5, 67, 0)
DeclareState("wheel2.omega", "wheel angular velocity [rad/s]", 8, 0.0, 0.0,0.0,\
0.0,0,544)
DeclareDerivative("wheel2.der(omega)", "der(wheel angular velocity) [rad/s2]", \
0.0, 0.0,0.0,0.0,0,576)
DeclareVariable("wheel2.Fxy", "Tire Force combined [N]", 0.0, 0.0,0.0,0.0,0,512)
DeclareVariable("wheel2.delta", "[rad|deg]", 0, 0.0,0.0,0.0,0,513)
DeclareAlias2("wheel2.Fz", "[N]", "chassis.Fzr", 1, 5, 44, 0)
DeclareAlias2("wheel2.Fxw", "[N]", "Fxr", 1, 3, 1, 0)
DeclareAlias2("wheel2.Fyw", "[N]", "chassis.Fyr", 1, 5, 46, 0)
DeclareAlias2("wheel2.Fxv", "[N]", "Fxr", 1, 3, 1, 0)
DeclareAlias2("wheel2.Fyv", "[N]", "chassis.Fyr", 1, 5, 46, 0)
DeclareVariable("wheel2.Drive_torque", "[N.m]", 0.0, 0.0,0.0,0.0,0,512)
DeclareAlias2("wheel2.Brake_torque", "[N.m]", "chassis.Tbw", 1, 5, 50, 0)
DeclareVariable("wheel2.sxy", "combined slip", 0.0, 0.0,0.0,0.0,0,512)
DeclareVariable("wheel2.fsxy", "tire coefficient", 0.0, 0.0,0.0,0.0,0,512)
DeclareVariable("wheel2.sx", "longitudinal slip [1]", 0.0, 0.0,0.0,0.0,0,512)
DeclareVariable("wheel2.sy", "Lateral slip [1]", 0.0, 0.0,0.0,0.0,0,512)
DeclareAlias2("wheel2.Je", "Engine inertia [J.s2.rad-1]", "chassis.Je", 1, 7, 106,\
 0)
DeclareAlias2("wheel2.i_T", "gear and final drive ratio product", "trans.i_T", 1,\
 5, 26, 0)
DeclareInput("Aped", "[:#(prefix=input)]", 0, 0.0, 0.0,0.0,0.0,0,512)
DeclareInput("Bped", "[:#(prefix=input)]", 1, 0.0, 0.0,0.0,0.0,0,512)
DeclareInput("swa", "[:#(prefix=input)]", 2, 0.0, 0.0,0.0,0.0,0,512)
DeclareInput("theta", "[:#(prefix=input)]", 3, 0.0, 0.0,0.0,0.0,0,512)
DeclareInput("r_gear", "[:#(prefix=input)]", 4, 0.0, 0.0,0.0,0.0,0,512)
DeclareParameter("hf", "", 117, 1, 0.0,0.0,0.0,0,560)
DeclareParameter("st_agear", "[:#(type=Integer)]", 118, 4, 0.0,0.0,0.0,0,564)
DeclareOutput("vx", "[m/s]", 0, 0.0, 0.0,0.0,0.0,0,512)
DeclareOutput("Fxr", "[N]", 1, 0.0, 0.0,0.0,0.0,0,512)
DeclareOutput("x", "", 2, 0, 0.0,0.0,0.0,0,512)
DeclareOutput("y", "", 3, 0, 0.0,0.0,0.0,0,512)
DeclareOutput("ax", "[m/s2]", 4, 0.0, 0.0,0.0,0.0,0,512)
DeclareOutput("Fyf", "[N]", 5, 0.0, 0.0,0.0,0.0,0,512)
DeclareOutput("delta", "[rad]", 6, 0.0, 0.0,0.0,0.0,0,512)
DeclareOutput("decl", "[m/s2]", 7, 0, 0.0,0.0,0.0,0,512)
DeclareOutput("agear", "[:#(type=Integer)]", 8, 0, 0.0,0.0,0.0,0,644)
DeclareOutput("ay", "[m/s2]", 9, 0.0, 0.0,0.0,0.0,0,512)
DeclareOutput("yaw_velocity", "[s-1]", 10, 0, 0.0,0.0,0.0,0,512)
EndNonAlias(0)

#define DymolaHaveUpdateInitVars 1
#include <dsblock5.c>

DYMOLA_STATIC void UpdateInitVars(double*time, double* X_, double* XD_, double* U_, double* DP_, int IP_[], Dymola_bool LP_[], double* F_, double* Y_, double* W_, double QZ_[], double duser_[], int iuser_[], void*cuser_[],struct DYNInstanceData*did_) {
static Real initStore[2];
if (DYNHReject) DYNX(F_,8)=initStore[0]; else initStore[0]=DYNX(F_,8);
}
StartDataBlock
StartPreBlock
pre(DYNX(W_,25),"trans.agear", DYNX(W_,24), 0);
EndPreBlock
StartEqBlock
DoRemember_(DYNX(Y_,4), 0.0, 0);
DoRemember_(DYNX(Y_,9), 0.0, 1);
DoRemember_(DYNX(F_,4), 0.0, 6);
DoRemember_(DYNX(F_,7), 0.0, 2);
DoRemember_(DYNX(F_,8), 0.0, 5);
DoRemember_(DYNX(W_,30), 0.0, 4);
DoRemember_(DYNX(W_,32), 0.0, 3);
EndEqBlock
UpdateQEvaluate(2)
EndDataBlock
